### ISSUE TITLE
Return value from `malloc_row` is not checked for NULL

### ISSUE THREAD

**Issue by Costava** [PhilippHochmann/ctable#1]
The function `malloc_row` in `src/table.c` can return `NULL` if memory allocation fails:

https://github.com/PhilippHochmann/ctable/blob/e9ac72d79177474be4b28f7584f2e5aefc5f6f2e/src/table.c#L43-L46

The functions `append_row` and `get_empty_table` call `malloc_row` but do not check the return value for `NULL`:

https://github.com/PhilippHochmann/ctable/blob/e9ac72d79177474be4b28f7584f2e5aefc5f6f2e/src/table.c#L69-L79
https://github.com/PhilippHochmann/ctable/blob/e9ac72d79177474be4b28f7584f2e5aefc5f6f2e/src/table.c#L110-L123

**Comment by PHochmann** [comment]
See https://github.com/PhilippHochmann/ctable/commit/0eaaa02e06a62b8ae938778c24d60fd6a6b8a055
