### ISSUE TITLE
vec_create function does not check malloc return value for NULL

### ISSUE THREAD

**Issue by Costava** [PhilippHochmann/ctable#2]
The function `vec_create` calls `malloc` but does not check the return value for `NULL`:

https://github.com/PhilippHochmann/ctable/blob/e9ac72d79177474be4b28f7584f2e5aefc5f6f2e/src/vector.c#L25-L38

`vec_create` is called by `strbuilder_create` is called by `add_cell_vfmt` which can pass the `NULL` as the `text` argument to `add_cell_internal` where it is assigned to the `text` member of a `Cell` struct (last line below):

https://github.com/PhilippHochmann/ctable/blob/e9ac72d79177474be4b28f7584f2e5aefc5f6f2e/src/table.c#L15-L24

This seems to create a large separation between where the problem is created (`NULL` returned from `malloc`) and where the problem will be noticed.

**Comment by PHochmann** [comment]
What would be appropiate behaviour when malloc fails? For example logging to stderr and locking the current table?

**Comment by Costava** [comment]
When malloc fails, easiest would be to print to `stderr` and `exit`. Fail and bail.

Otherwise, propagating the error up through the calling functions and the user would have to check that `add_cell` succeeded.

For how often running out of memory would happen, printing to `stderr` and `exit` may be acceptable.

`malloc` could be swapped out with a wrapper function:
```
// Equivalent to malloc but prints to stderr and exits if there is an error
// Do not easy_malloc(0) since implementations are permitted to return NULL from malloc(0)
void *easy_malloc(size_t size)
{
    void *const ptr = malloc(size);

    if (ptr == NULL)
    {
        fprintf(stderr, "%s: Failed to malloc %zu bytes\n", __func__, size);
        exit(1);
    }

    return ptr;
}
```

**Comment by PHochmann** [comment]
See https://github.com/PhilippHochmann/ctable/commit/0eaaa02e06a62b8ae938778c24d60fd6a6b8a055
