### ISSUE TITLE
Possible extension: fprint_table

### ISSUE THREAD

**Issue by Costava** [PhilippHochmann/ctable#3]
The function `void print_table(Table *table)` prints to `stdout`.
`stdout` is like any FILE pointer though.
Possible new function could be `void fprint_table(FILE *stream, Table *table)` that does the same as `print_table` but a different FILE pointer can be specified.

The naming mirrors the relationship of `printf` and `fprintf` where `fprintf` is the same but allows any FILE pointer to be used.

**Comment by PHochmann** [comment]
It's the making, it's not a big change to make :)

**Comment by PHochmann** [comment]
See https://github.com/PhilippHochmann/ctable/commit/44682e9a2b5c3070d2eda38c9c326e5489e72ce1
